### ISSUE TITLE
Mise en forme possible dans les libellés candidat des PJ ?

### ISSUE THREAD

**Issue by cyrilbourreau** [EsupPortail/esup-ecandidat#36]
Bonjour,
je voudrais savoir si, dans les libellés candidat des pièces justificatives, on peut utiliser du code de mise en forme ? Je serais particulièrement intéressé pour effectuer un saut de ligne par exemple, car les textes longs des libellés sont parfois un peu trop compacts sur la plateforme tels qu'ils s'affichent aux candidats.

**Comment by j-kwan** [comment]
Bonjour,

Nous rencontrons aussi des soucis de personnalisations de l'outil (d'où  [mon ticket](https://github.com/EsupPortail/esup-ecandidat/issues/30) pour forcer certaines modifications).

La seule possibilité que j'ai trouvé est de surcharger le CSS en ajoutant du code à la fin du fichier `WEB-INF/classes/VAADIN/themes/valo-ul/styles.css` :

```css
/**
 * PERSONNALISATION
 */
/* Tableau de l'offre de formation : retour à la ligne + correction de la hauteur de ligne */
div.v-treetable td.v-table-cell-content div {
  white-space: normal;
  line-height: initial !important;
}
```
Apparemment, les ressources telles que le fichier CSS est mis en cache. Donc après modification de la feuille de style, il faut relancer le serveur Tomcat pour que la modification soit prise en compte.

En espérant avoir pu vous aider,
